---
- name: Prepare join command for the other control nodes
  hosts: master01
  become: true
  tasks:
    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join workers
  hosts: master
  become: true
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      ansible.builtin.wait_for: "host={{ hostvars['master01']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"

    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['master01'].join_command }}--control-plane >> node_joined.log"
      args:
        chdir: /home/skogen
        creates: node_joined.log
      when: inventory_hostname != "master01"
